In [2]:
import pandas as pd

In [2]:
import datetime as dt
date = dt.datetime.now()
print(date)

2023-07-13 19:05:40.816708

In [3]:
print(date.year)

2023

In [4]:
print(date.month)

7

In [5]:
print(date.strftime("%B"))

July

In [9]:
# "%A" - use for day
# "%B" - use for month

print("Day :" + date.strftime("%A"))
print("Month : "+ date.strftime("%B"))
print("Date : " + date.strftime("%C"))
print("Month/Date/Year : " + date.strftime("%D"))
print("Year-Month-Date : " + date.strftime("%F"))
print("Only Year : " + date.strftime("%G"))
print("Only Hours in 24 format : " + date.strftime("%H"))
print("Only Minutes  : " + date.strftime("%M"))
print("Indian format : " + date.strftime("%c"))

Day :Thursday
Month : July
Date : 20
Month/Date/Year : 07/13/23
Year-Month-Date : 2023-07-13
Only Year : 2023
Only Hours in 24 format : 19
Only Minutes  : 05
Indian format : Thu Jul 13 19:05:40 2023

## Some of the important format for datetime

In [3]:
data = pd.read_csv("./Datasets/Datetime_format.csv")
data

,Directive,Meaning,Example
0,%a,Abbreviated weekday name.,"Sun, Mon, ..."
1,%A,Full weekday name.,"Sunday, Monday, ..."
2,%w,Weekday as a decimal number.,"0, 1, ..., 6"
3,%d,Day of the month as a zero-padded decimal.,"01, 02, ..., 31"
4,%-d,Day of the month as a decimal number.,"1, 2, ..., 30"
5,%b,Abbreviated month name.,"Jan, Feb, ..., Dec"
6,%B,Full month name.,"January, February, ..."
7,%m,Month as a zero-padded decimal number.,"01, 02, ..., 12"
8,%-m,Month as a decimal number.,"1, 2, ..., 12"
9,%y,Year without century as a zero-padded decimal ...,"00, 01, ..., 99"
10,%-y,Year without century as a decimal number.,"0, 1, ..., 99"
11,%Y,Year with century as a decimal number.,"2013, 2019 etc."
12,%H,Hour (24-hour clock) as a zero-padded decimal ...,"00, 01, ..., 23"
13,%-H,Hour (24-hour clock) as a decimal number.,"0, 1, ..., 23"
14,%I,Hour (12-hour clock) as a zero-padded decimal ...,"01, 02, ..., 12"
15,%-I,Hour (12-hour clock) as a decimal number.,"1, 2, ... 12"
16,%p,Locale’s AM or PM.,"AM, PM"
17,%M,Minute as a zero-padded decimal number.,"00, 01, ..., 59"
18,%-M,Minute as a decimal number.,"0, 1, ..., 59"
19,%S,Second as a zero-padded decimal number.,"00, 01, ..., 59"
20,%-S,Second as a decimal number.,"0, 1, ..., 59"
21,%f,"Microsecond as a decimal number, zero-padded o...",000000 - 999999
22,%z,UTC offset in the form +HHMM or -HHMM.,
23,%Z,Time zone name.,
24,%j,Day of the year as a zero-padded decimal number.,"001, 002, ..., 366"
25,%-j,Day of the year as a decimal number.,"1, 2, ..., 366"
26,%U,Week number of the year (Sunday as the first d...,"00, 01, ..., 53"
27,%W,Week number of the year (Monday as the first d...,"00, 01, ..., 53"
28,%c,Locale’s appropriate date and time representat...,Mon Sep 30 07:06:05 2013
29,%x,Locale’s appropriate date representation.,9/30/2013
30,%X,Locale’s appropriate time representation.,7:06:05
31,%%,A literal '%' character.,%